[program:amigo-secreto-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/amigo-secreto/artisan queue:work --sleep=1 --tries=3 --timeout=120 --backoff=5
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/amigo-secreto/storage/logs/queue-worker.log
stopwaitsecs=3600
